/**
 * Records the golden runs: complete games, played by fixed policies, together with the score the engine gives them,
 * and the digest of what a game starts from. `pnpm record-golden-runs` rewrites `shared/game/testing/golden-runs.ts`:
 * do it after bumping ENGINE_VERSION on purpose, never to silence a failing test.
 */
import { writeFileSync } from 'node:fs';
import { ENGINE_VERSION } from '../shared/game/replay.ts';
import { layoutDigest } from '../shared/game/testing/layout-digest.ts';
import { hunter, noisyPolicy, recordRun, wanderer } from '../shared/game/testing/policies.ts';

const runs = [
  { name: 'hunter that aims at what matters', ...recordRun(hunter) },
  { name: 'wanderer with a mouse-like hand, seed 3', ...recordRun(wanderer(3)) },
  { name: 'random controls, seed 7', ...recordRun(noisyPolicy(7)) },
  { name: 'random controls, seed 2026', ...recordRun(noisyPolicy(2026)) },
];

const entries = runs
  .map(
    ({ name, score, ticks, replay }) =>
      `  {\n    name: '${name}',\n    score: ${score},\n    ticks: ${ticks},\n    replay: [${replay.join(', ')}],\n  },`,
  )
  .join('\n');

const source = `// Generated by \`pnpm record-golden-runs\`: do not edit by hand.
export const GOLDEN_RUNS_ENGINE_VERSION = ${ENGINE_VERSION};

export const GOLDEN_LAYOUT_DIGEST = '${await layoutDigest()}';

export const GOLDEN_RUNS: ReadonlyArray<{ name: string; score: number; ticks: number; replay: readonly number[] }> = [
${entries}
];
`;

writeFileSync(new URL('../shared/game/testing/golden-runs.ts', import.meta.url), source);
for (const { name, score, ticks } of runs) console.log(`${name}: score ${score} in ${ticks} ticks`);
